# Generated by Django 5.0.14 on 2025-11-08 21:39

import analise.models.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), analise.models.validators.validate_cpf], verbose_name='CPF')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(validators=[analise.models.validators.validate_data_nascimento], verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nacionalidade')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.5)], verbose_name='Altura')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(250.0)], verbose_name='Peso (kg)')),
                ('esporte', models.CharField(choices=[('FUTEBOL', 'futebol'), ('BASQUETE', 'basquete'), ('CORRIDA', 'corrida'), ('VÔLEI', 'vôlei'), ('NATAÇÃO', 'natação'), ('ATLETISMO', 'atletismo'), ('TÊNIS', 'tênis'), ('Não Especificado', 'não especificado')], default='Não Especificado', max_length=20, verbose_name='Esporte')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('local', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Local')),
                ('cidade', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Cidade')),
                ('pais', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Pais')),
                ('data', models.DateField(verbose_name='Data')),
                ('esporte', models.CharField(choices=[('FUTEBOL', 'futebol'), ('BASQUETE', 'basquete'), ('CORRIDA', 'corrida'), ('VÔLEI', 'vôlei'), ('NATAÇÃO', 'natação'), ('ATLETISMO', 'atletismo'), ('TÊNIS', 'tênis'), ('Não Especificado', 'não especificado')], default='Não Especificado', max_length=20, verbose_name='Esporte')),
                ('oficial', models.BooleanField(default=True, verbose_name='Evento Oficial')),
                ('organizador', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Organizador')),
                ('capacidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pontuação')),
                ('assistencias', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Assistências')),
                ('faltas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Faltas')),
                ('cartoes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cartões')),
                ('minutos_jogados', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minutos Jogados')),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distância')),
                ('observacoes', models.TextField(blank=True, default='', max_length=2000, verbose_name='Observações')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='analise.atleta', verbose_name='Atleta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='analise.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatisticas',
            },
        ),
    ]
